# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b19743b1f9a2371b5ac7afef2af92dbc7f1177b92c346497a744f0597f0fb12fe743d1004c17b7e9ed6aef344b867998ddf6e24fac893953acbaafe504c66d6a

test:
  secret_key_base: a5aed6538c052bf6a910c88777316c4055cf5f2bb252823766640f05abad9be681a6aa2b0af71d7e5361df0e767adb34f0b4f4f17dd348ce1ba75398dfbcdcee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
